name: docker-image

on:
  push:
    branches:
      - "master"

env:
  REGISTRY: ghcr.io
  TEST_TAG: ghcr.io/super-bunny/barotrauma-server:test
  LATEST_TAG: ghcr.io/super-bunny/barotrauma-server:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build and export to Docker
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          load: true
#          tags: ${{ env.TEST_TAG }}
#
#      - name: Test
#        run: |
#          docker run --rm ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
